// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_me from "./routes/api/me.ts";
import * as $api_oauth_callback from "./routes/api/oauth/callback.ts";
import * as $api_oauth_initiate from "./routes/api/oauth/initiate.ts";
import * as $api_server_describe from "./routes/api/server/describe.ts";
import * as $api_server_migrate from "./routes/api/server/migrate.ts";
import * as $api_server_migrate_create from "./routes/api/server/migrate/create.ts";
import * as $api_server_migrate_data from "./routes/api/server/migrate/data.ts";
import * as $api_server_migrate_finalize from "./routes/api/server/migrate/finalize.ts";
import * as $api_server_migrate_identity from "./routes/api/server/migrate/identity.ts";
import * as $api_server_migrate_identity_request from "./routes/api/server/migrate/identity/request.ts";
import * as $api_server_migrate_identity_sign from "./routes/api/server/migrate/identity/sign.ts";
import * as $index from "./routes/index.tsx";
import * as $login_callback from "./routes/login/callback.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $migrate_index from "./routes/migrate/index.tsx";
import * as $migrate_progress from "./routes/migrate/progress.tsx";
import * as $AirportSign from "./islands/AirportSign.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $HandleInput from "./islands/HandleInput.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $LoginMethodSelector from "./islands/LoginMethodSelector.tsx";
import * as $MigrationFlow from "./islands/MigrationFlow.tsx";
import * as $MigrationProgress from "./islands/MigrationProgress.tsx";
import * as $MigrationSetup from "./islands/MigrationSetup.tsx";
import * as $OAuthCallback from "./islands/OAuthCallback.tsx";
import * as $PasswordLogin from "./islands/PasswordLogin.tsx";
import * as $Ticket from "./islands/Ticket.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/me.ts": $api_me,
    "./routes/api/oauth/callback.ts": $api_oauth_callback,
    "./routes/api/oauth/initiate.ts": $api_oauth_initiate,
    "./routes/api/server/describe.ts": $api_server_describe,
    "./routes/api/server/migrate.ts": $api_server_migrate,
    "./routes/api/server/migrate/create.ts": $api_server_migrate_create,
    "./routes/api/server/migrate/data.ts": $api_server_migrate_data,
    "./routes/api/server/migrate/finalize.ts": $api_server_migrate_finalize,
    "./routes/api/server/migrate/identity.ts": $api_server_migrate_identity,
    "./routes/api/server/migrate/identity/request.ts":
      $api_server_migrate_identity_request,
    "./routes/api/server/migrate/identity/sign.ts":
      $api_server_migrate_identity_sign,
    "./routes/index.tsx": $index,
    "./routes/login/callback.tsx": $login_callback,
    "./routes/login/index.tsx": $login_index,
    "./routes/migrate/index.tsx": $migrate_index,
    "./routes/migrate/progress.tsx": $migrate_progress,
  },
  islands: {
    "./islands/AirportSign.tsx": $AirportSign,
    "./islands/Counter.tsx": $Counter,
    "./islands/HandleInput.tsx": $HandleInput,
    "./islands/Header.tsx": $Header,
    "./islands/LoginMethodSelector.tsx": $LoginMethodSelector,
    "./islands/MigrationFlow.tsx": $MigrationFlow,
    "./islands/MigrationProgress.tsx": $MigrationProgress,
    "./islands/MigrationSetup.tsx": $MigrationSetup,
    "./islands/OAuthCallback.tsx": $OAuthCallback,
    "./islands/PasswordLogin.tsx": $PasswordLogin,
    "./islands/Ticket.tsx": $Ticket,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
